/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final Program n);

  public void visit(final MainClass n);

  public void visit(final TypeDeclaration n);

  public void visit(final ClassDecl n);

  public void visit(final ClassExtendsDeclaration n);

  public void visit(final VarDecl n);

  public void visit(final MethodDecl n);

  public void visit(final FormalList n);

  public void visit(final FormalParameter n);

  public void visit(final FormalRest n);

  public void visit(final Type n);

  public void visit(final ArrayType n);

  public void visit(final BooleanType n);

  public void visit(final IntegerType n);

  public void visit(final Statement n);

  public void visit(final Block n);

  public void visit(final AssignmentStatement n);

  public void visit(final ArrayAssignmentStatement n);

  public void visit(final IfStatement n);

  public void visit(final WhileStatement n);

  public void visit(final PrintStatement n);

  public void visit(final Exp n);

  public void visit(final AndExpression n);

  public void visit(final CompareExpression n);

  public void visit(final PlusExpression n);

  public void visit(final MinusExpression n);

  public void visit(final TimesExpression n);

  public void visit(final ArrayLookup n);

  public void visit(final ArrayLength n);

  public void visit(final MessageSend n);

  public void visit(final ExpList n);

  public void visit(final ExpRest n);

  public void visit(final PrimaryExpression n);

  public void visit(final IntegerLiteral n);

  public void visit(final TrueLiteral n);

  public void visit(final FalseLiteral n);

  public void visit(final Identifier n);

  public void visit(final ThisExpression n);

  public void visit(final ArrayAllocationExpression n);

  public void visit(final AllocationExpression n);

  public void visit(final NotExpression n);

  public void visit(final BracketExpression n);

}
