/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class MethodDecl implements INode {

  public NodeToken f0;

  public Type f1;

  public NodeToken f2;

  public NodeToken f3;

  public NodeOptional f4;

  public NodeToken f5;

  public NodeToken f6;

  public NodeListOptional f7;

  public NodeListOptional f8;

  public NodeToken f9;

  public Exp f10;

  public NodeToken f11;

  public NodeToken f12;

  private static final long serialVersionUID = 144L;

  public MethodDecl(final NodeToken n0, final Type n1, final NodeToken n2, final NodeToken n3, final NodeOptional n4, final NodeToken n5, final NodeToken n6, final NodeListOptional n7, final NodeListOptional n8, final NodeToken n9, final Exp n10, final NodeToken n11, final NodeToken n12) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
    f12 = n12;
  }

  public MethodDecl(final Type n0, final NodeToken n1, final NodeOptional n2, final NodeListOptional n3, final NodeListOptional n4, final Exp n5) {
    f0 = new NodeToken("public");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("(");
    f4 = n2;
    f5 = new NodeToken(")");
    f6 = new NodeToken("{");
    f7 = n3;
    f8 = n4;
    f9 = new NodeToken("return");
    f10 = n5;
    f11 = new NodeToken(";");
    f12 = new NodeToken("}");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
